#!/bin/sh
# Build the SVG icon sprite served by the web portal.
#
# Every line of the icon list names one Lucide icon and the symbol id it gets
# in the sprite, separated by a colon:
#
#   lucide-name:symbol-id
#
# The sprite is inlined into every page by the layout, so the symbols are
# referenced as same document fragments and no extra request is made.
#
# usage: fetch-icons.sh [ICONLIST] [OUTPUT]
set -eu

LUCIDE_VERSION="${LUCIDE_VERSION:-0.469.0}"
BASE_URL="https://raw.githubusercontent.com/lucide-icons/lucide/${LUCIDE_VERSION}/icons"

iconlist="${1:-tools/icons.list}"
output="${2:-web/static/img/icons.svg}"

if [ ! -f "$iconlist" ]; then
	echo "fetch-icons: icon list not found: $iconlist" >&2
	exit 1
fi

if ! command -v curl >/dev/null 2>&1; then
	echo "fetch-icons: curl is required" >&2
	exit 1
fi

mkdir -p "$(dirname "$output")"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT INT TERM

{
	printf '<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" style="position:absolute;width:0;height:0;overflow:hidden" focusable="false">\n'
	printf '<!-- Icons from Lucide %s, licensed under the ISC License.\n' "$LUCIDE_VERSION"
	printf '     Generated by tools/fetch-icons.sh, do not edit by hand. -->\n'
	printf '<defs>\n'
} >"$tmp"

failed=0
count=0

while IFS= read -r line || [ -n "$line" ]; do
	case "$line" in
	'' | \#*) continue ;;
	esac

	source_name="${line%%:*}"
	symbol_id="${line#*:}"
	if [ -z "$source_name" ] || [ -z "$symbol_id" ] || [ "$source_name" = "$line" ]; then
		echo "fetch-icons: malformed line: $line" >&2
		failed=$((failed + 1))
		continue
	fi

	svg="$(curl -fsSL --retry 3 --retry-delay 1 --max-time 20 "${BASE_URL}/${source_name}.svg" 2>/dev/null || true)"
	if [ -z "$svg" ]; then
		echo "fetch-icons: could not download ${source_name}" >&2
		failed=$((failed + 1))
		continue
	fi

	inner="$(printf '%s' "$svg" | tr '\n' ' ' | sed -e 's/^.*<svg[^>]*>//' -e 's|</svg>.*$||' -e 's/  */ /g')"
	if [ -z "$inner" ]; then
		echo "fetch-icons: empty icon body for ${source_name}" >&2
		failed=$((failed + 1))
		continue
	fi

	{
		printf '<symbol id="icon-%s" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">' "$symbol_id"
		printf '%s' "$inner"
		printf '</symbol>\n'
	} >>"$tmp"
	count=$((count + 1))
done <"$iconlist"

printf '</defs>\n</svg>\n' >>"$tmp"

if [ "$count" -eq 0 ]; then
	echo "fetch-icons: no icons were built, keeping the existing sprite" >&2
	exit 1
fi

cat "$tmp" >"$output"
echo "fetch-icons: wrote $count symbols to $output"

if [ "$failed" -ne 0 ]; then
	echo "fetch-icons: $failed icons failed" >&2
	exit 1
fi
