package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
	"time"
)

func (s *server) writePinOverride(pins map[string]string) error {
	if len(pins) == 0 {
		_ = os.Remove(s.overridePath)
		return nil
	}
	var b strings.Builder
	b.WriteString("# Generated by snikket-updater. Do not edit by hand.\n")
	b.WriteString("services:\n")
	names := make([]string, 0, len(pins))
	for name := range pins {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		fmt.Fprintf(&b, "  %s:\n    image: %s\n", name, pins[name])
	}
	return os.WriteFile(s.overridePath, []byte(b.String()), overrideFileMode)
}

func (s *server) snapshot() statusResponse {
	s.mu.Lock()
	defer s.mu.Unlock()
	status := "idle"
	phase := s.phase
	if phase == "" {
		phase = "idle"
	}
	if s.busy {
		status = "busy"
	}
	resp := statusResponse{
		Status:        status,
		Phase:         phase,
		Available:     s.available,
		IntervalHours: s.settings.IntervalHours,
		AutoUpdate:    s.settings.AutoUpdate,
		PinDigests:    s.settings.PinDigests,
		Services:      append([]serviceState(nil), s.services...),
		Detail:        s.detail,
		Configured:    true,
		ImagePrefix:   s.imagePrefix,
		VerifyEnabled: s.verifyEnabled,
		RequireVerify: s.requireVerify,
	}
	if !s.lastCheck.IsZero() {
		resp.LastCheck = s.lastCheck.Format(time.RFC3339)
	}
	if !s.lastApply.IsZero() {
		resp.LastApply = s.lastApply.Format(time.RFC3339)
	}
	if s.job != nil {
		jobCopy := *s.job
		jobCopy.Steps = append([]jobStep(nil), s.job.Steps...)
		jobCopy.Log = append([]string(nil), s.job.Log...)
		resp.Job = &jobCopy
	}
	return resp
}

func (s *server) loadSettings() {
	data, err := os.ReadFile(s.statePath)
	if err != nil {
		return
	}
	var next settings
	if json.Unmarshal(data, &next) != nil {
		return
	}
	if next.IntervalHours > 0 {
		s.settings = next
	}
}

func (s *server) saveSettings() error {
	s.mu.Lock()
	defer s.mu.Unlock()
	data, err := json.MarshalIndent(s.settings, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(s.statePath, data, stateFileMode)
}

func (s *server) loadPins() {
	data, err := os.ReadFile(s.pinsPath)
	if err != nil {
		return
	}
	var body pinsFile
	if json.Unmarshal(data, &body) != nil || body.Services == nil {
		return
	}
	s.pins = body.Services
}

func (s *server) savePins() error {
	s.mu.Lock()
	body := pinsFile{Services: copyMap(s.pins)}
	s.mu.Unlock()
	data, err := json.MarshalIndent(body, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(s.pinsPath, data, stateFileMode)
}
