#!/bin/bash

set -eo pipefail

# shellcheck source=lib/compose.sh
source "$(cd "$(dirname "$0")" && pwd)/lib/compose.sh"

snikketx_cd_root

FROM_DIR=""
BACKUP_DIR=""
YES=0

usage() {
	cat <<'EOF'
Usage: ./scripts/migrate-from-snikket.sh --from /path/to/classic/snikket [--backup-dir /abs/path] [--yes]

Migrates a classic Snikket install to this SnikketX checkout without losing
Prosody data (accounts, MAM chats, MUCs, uploads).

Steps:
  1. Full backup (mandatory)
  2. Stop classic containers
  3. Reuse classic snikket_data volume via deploy/migrate/docker-compose.migrate.yml
  4. Import snikket.conf and write .env
  5. Preflight + start SnikketX
  6. Print rollback instructions

Keep the classic directory until you trust the new stack.
EOF
}

while [[ $# -gt 0 ]]; do
	case "$1" in
	-h | --help)
		usage
		exit 0
		;;
	--from)
		FROM_DIR="$2"
		shift 2
		;;
	--backup-dir)
		BACKUP_DIR="$2"
		shift 2
		;;
	--yes | -y)
		YES=1
		shift
		;;
	*)
		echo "Unknown argument: $1" >&2
		usage >&2
		exit 1
		;;
	esac
done

if [[ -z "$FROM_DIR" || ! -d "$FROM_DIR" ]]; then
	echo "--from DIR is required and must exist" >&2
	usage >&2
	exit 1
fi
FROM_DIR="$(cd "$FROM_DIR" && pwd)"

if [[ -z "$BACKUP_DIR" ]]; then
	BACKUP_DIR="$(pwd)/backups"
fi
mkdir -p "$BACKUP_DIR"
BACKUP_DIR="$(cd "$BACKUP_DIR" && pwd)"

if [[ "$YES" -ne 1 ]]; then
	echo "This will stop the classic Snikket stack in ${FROM_DIR}"
	echo "after writing a backup under ${BACKUP_DIR}."
	echo -n "Continue? [y/N] "
	read -r -n1 ans
	echo ""
	case "$ans" in
	y | Y) ;;
	*)
		echo "Aborting."
		exit 1
		;;
	esac
fi

echo "== 1/6 Backup =="
./scripts/backup.sh "$BACKUP_DIR"
# Point at newest backup dir
LATEST=$(ls -1dt "$BACKUP_DIR"/snikketx-backup-* 2>/dev/null | head -n1)
if [[ -z "$LATEST" ]]; then
	echo "Backup failed to produce a directory." >&2
	exit 1
fi
echo "Using backup ${LATEST}"
printf '%s\n' "$LATEST" >"$BACKUP_DIR/LAST_PRE_MIGRATE"
printf '%s\n' "$FROM_DIR" >"$BACKUP_DIR/LAST_CLASSIC_FROM"

echo "== 2/6 Stop classic stack =="
if [[ -f "$FROM_DIR/docker-compose.yml" ]]; then
	(cd "$FROM_DIR" && docker compose down) || true
fi
for c in snikket snikket-proxy snikket-portal snikket-certs snikket-web-proxy; do
	docker stop "$c" >/dev/null 2>&1 || true
done

echo "== 3/6 Locate classic data volume =="
CLASSIC_VOL=""
for cand in snikket_snikket_data snikket-selfhosted_snikket_data snikketx_snikket_data; do
	if docker volume inspect "$cand" >/dev/null 2>&1; then
		CLASSIC_VOL="$cand"
		break
	fi
done
# Fallback: volume attached to stopped snikket container
if [[ -z "$CLASSIC_VOL" ]] && docker container inspect snikket >/dev/null 2>&1; then
	CLASSIC_VOL=$(docker inspect -f '{{range .Mounts}}{{if eq .Destination "/snikket"}}{{.Name}}{{end}}{{end}}' snikket)
fi
if [[ -z "$CLASSIC_VOL" ]]; then
	echo "Could not find classic snikket_data volume. Restore from backup into a fresh volume instead." >&2
	exit 1
fi
echo "Classic volume: ${CLASSIC_VOL}"

mkdir -p deploy/migrate
cat >deploy/migrate/docker-compose.migrate.yml <<EOF
# Generated by migrate-from-snikket.sh. Reuses classic Prosody data.
volumes:
  snikket_data:
    external: true
    name: ${CLASSIC_VOL}
EOF
echo "Wrote deploy/migrate/docker-compose.migrate.yml"

echo "== 4/6 Import config =="
if [[ -f "$FROM_DIR/snikket.conf" ]]; then
	cp -a "$FROM_DIR/snikket.conf" ./snikket.conf
elif [[ -f "$LATEST/snikket.conf" ]]; then
	cp -a "$LATEST/snikket.conf" ./snikket.conf
else
	echo "No snikket.conf found in classic dir or backup." >&2
	exit 1
fi
domain=$(snikketx_conf_get SNIKKET_DOMAIN)
email=$(snikketx_conf_get SNIKKET_ADMIN_EMAIL)
secret=$(snikketx_random 32)
admin_pw=$(snikketx_random 24)
updater_token=$(snikketx_random 32)
backup_token=$(snikketx_random 32)
cat >.env <<EOF
SNIKKET_DOMAIN=${domain}
SNIKKET_ADMIN_EMAIL=${email}
RG_CHALLENGE_SECRET=${secret}
RG_ADMIN_BOOTSTRAP_PASSWORD=${admin_pw}
SNIKKET_UPDATER_TOKEN=${updater_token}
SNIKKET_BACKUP_TOKEN=${backup_token}
EOF
echo "Wrote .env for domain ${domain}"

echo "== 5/6 Preflight + start =="
./scripts/preflight.sh || true
./scripts/start.sh

echo "== 6/6 Verify =="
sleep 3
./scripts/status.sh || true

cat <<EOF

Migration started for ${domain}.
Backup kept at: ${LATEST}
Classic compose kept at: ${FROM_DIR}

If something is wrong:
  ./scripts/rollback-to-snikket.sh --from ${FROM_DIR} --backup-dir ${LATEST}

When you trust SnikketX, you can remove deploy/migrate/docker-compose.migrate.yml
only after copying data into a native snikketx_snikket_data volume (optional).
EOF
