#!/bin/bash
# Render Traefik dynamic routes from snikket.conf / .env into
# deploy/traefik/dynamic.yml. The file provider watches it, so re-running is
# enough for route changes. Called by start.sh and update.sh.

set -eo pipefail

# shellcheck source=lib/compose.sh
source "$(cd "$(dirname "$0")" && pwd)/lib/compose.sh"

snikketx_cd_root

OUT="deploy/traefik/dynamic.yml"
MODE="${1:-prod}"

domain="$(snikketx_domain)"
domain="${domain:-${SNIKKET_DOMAIN:-}}"
if [[ -z "$domain" ]]; then
	echo "SNIKKET_DOMAIN is not set. Run ./scripts/init.sh or export it." >&2
	exit 1
fi

mkdir -p deploy/traefik

hosts_all="Host(\`${domain}\`) || Host(\`share.${domain}\`) || Host(\`groups.${domain}\`)"

prosody_paths='PathPrefix(`/upload`) || PathPrefix(`/chat`) || PathPrefix(`/http-bind`) || PathPrefix(`/xmpp-websocket`) || PathPrefix(`/admin_api`) || PathPrefix(`/invites_api`) || PathPrefix(`/invites_bootstrap`) || PathPrefix(`/.well-known/host-meta`) || PathPrefix(`/.well-known/host-meta.json`)'

if [[ "$MODE" == "dev" ]]; then
	entrypoint="web"
	acme_entrypoints="        - web"
	tls_block=""
	acme_tls=""
else
	entrypoint="websecure"
	acme_entrypoints="        - web
        - websecure"
	tls_block="      tls:
        certResolver: letsencrypt"
	acme_tls="      tls: {}"
fi

cat > "$OUT" <<EOF
# Generated by scripts/render-edge.sh for ${domain} (${MODE})
# Do not edit by hand. Re-run the script to regenerate.

http:
  routers:
    snikket-acme:
      rule: PathPrefix(\`/.well-known/acme-challenge\`)
      entryPoints:
${acme_entrypoints}
      priority: 100
      service: snikket-acme
${acme_tls}

    snikket-prosody:
      rule: (${hosts_all}) && (${prosody_paths})
      entryPoints:
        - ${entrypoint}
      priority: 50
      service: snikket-prosody
${tls_block}

    snikket-web:
      rule: ${hosts_all}
      entryPoints:
        - ${entrypoint}
      priority: 10
      service: snikket-web
${tls_block}

  services:
    snikket-web:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://snikket_portal:5765

    snikket-prosody:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://snikket_server:5280

    snikket-acme:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://acme_webroot:8080
EOF

echo "Wrote ${OUT} (${MODE}, domain ${domain})"
