#!/bin/bash
# Render Traefik dynamic routes from snikket.conf / .env

set -eo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${ROOT}/deploy/traefik/dynamic.yml"
CONF="${ROOT}/snikket.conf"
ENVFILE="${ROOT}/.env"
MODE="${1:-prod}"

domain=""
if [[ -f "$CONF" ]]; then
	domain=$(grep -E '^SNIKKET_DOMAIN=' "$CONF" | head -n1 | cut -d= -f2- | tr -d '"' | tr -d "'")
fi
if [[ -z "$domain" && -f "$ENVFILE" ]]; then
	domain=$(grep -E '^SNIKKET_DOMAIN=' "$ENVFILE" | head -n1 | cut -d= -f2- | tr -d '"' | tr -d "'")
fi
if [[ -z "$domain" ]]; then
	domain="${SNIKKET_DOMAIN:-}"
fi
if [[ -z "$domain" ]]; then
	echo "SNIKKET_DOMAIN is not set. Run ./scripts/init.sh or export it." >&2
	exit 1
fi

host_main="Host(\`${domain}\`)"
host_share="Host(\`share.${domain}\`)"
host_groups="Host(\`groups.${domain}\`)"
hosts_all="${host_main} || ${host_share} || ${host_groups}"

prosody_paths='PathPrefix(`/upload`) || PathPrefix(`/http-bind`) || PathPrefix(`/xmpp-websocket`) || PathPrefix(`/admin_api`) || PathPrefix(`/invites_api`) || PathPrefix(`/invites_bootstrap`) || PathPrefix(`/.well-known/host-meta`)'

if [[ "$MODE" == "dev" ]]; then
	cat > "$OUT" <<EOF
# Generated by scripts/render-edge.sh for ${domain} (dev)
# Do not edit by hand.

http:
  routers:
    snikket-prosody:
      rule: (${hosts_all}) && (${prosody_paths})
      entryPoints:
        - web
      priority: 50
      service: snikket-prosody

    snikket-web:
      rule: ${hosts_all}
      entryPoints:
        - web
      priority: 10
      service: ravenguard

  services:
    ravenguard:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://ravenguard:8080

    snikket-prosody:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://snikket_server:5280
EOF
else
	cat > "$OUT" <<EOF
# Generated by scripts/render-edge.sh for ${domain} (prod)
# Do not edit by hand.

http:
  middlewares:
    redirect-https:
      redirectScheme:
        scheme: https
        permanent: true

  routers:
    acme-challenge:
      rule: PathPrefix(\`/.well-known/acme-challenge\`)
      entryPoints:
        - web
      priority: 100
      service: acme-webroot

    http-redirect:
      rule: ${hosts_all}
      entryPoints:
        - web
      priority: 1
      middlewares:
        - redirect-https
      service: ravenguard

    snikket-prosody:
      rule: (${hosts_all}) && (${prosody_paths})
      entryPoints:
        - websecure
      priority: 50
      service: snikket-prosody
      tls:
        certResolver: letsencrypt

    snikket-web:
      rule: ${hosts_all}
      entryPoints:
        - websecure
      priority: 10
      service: ravenguard
      tls:
        certResolver: letsencrypt

  services:
    ravenguard:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://ravenguard:8080

    snikket-prosody:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://snikket_server:5280

    acme-webroot:
      loadBalancer:
        servers:
          - url: http://acme_webroot:8080
EOF
fi

echo "Wrote ${OUT} for domain ${domain} (${MODE})"
